services:
  connect:
    image: quay.io/debezium/connect:latest
    container_name: connect
    ports:
      - "8083:8083"
    volumes:
      - ./sa-key.json:/tmp/sa-key.json
    environment:
      BOOTSTRAP_SERVERS: bootstrap.transapp-rollback-poc.us-east4.managedkafka.pr-transapp-dev-use4-01.cloud.goog:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses

      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter


      CONNECT_REST_ADVERTISED_HOST_NAME: connect

      # Security for Kafka connection
      CONNECT_SECURITY_PROTOCOL: SASL_SSL
      CONNECT_SASL_MECHANISM: OAUTHBEARER
      CONNECT_SASL_JAAS_CONFIG: org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required;
      CONNECT_SASL_LOGIN_CALLBACK_HANDLER_CLASS: com.google.cloud.hosted.kafka.auth.GcpLoginCallbackHandler


