FROM debezium/connect:2.4

# Add the GCP IAM Kafka OAuth library

ADD https://github.com/googleapis/managedkafka/releases/download/v1.0.1/managed-kafka-auth-login-handler-1.0.1-jar-with-dependencies.jar /kafka/libs/

